swagger: '2.0'
info:
  title: greet-api
  description: Sample API on API Gateway with 2 Google Cloud Functions backends
  version: 1.0.0
schemes:
  - http
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://australia-southeast1-wabenwongtest.cloudfunctions.net/Helloworld
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /hardware/register:
    get:
      summary: Register a scale
      operationId: register
      x-google-backend:
        address: https://australia-southeast1-wabenwongtest.cloudfunctions.net/register
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /hardware/send:
    get:
      summary: Send a measurement
      operationId: send
      x-google-backend:
        address: https://australia-southeast1-wabenwongtest.cloudfunctions.net/send
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /hardware/email:
    get:
      summary: Gets an email
      operationId: email
      x-google-backend:
        address: http://australia-southeast1-wabenwongtest.cloudfunctions.net/email
      responses:
        '200':
          description: A successful response
          schema:
            type: string