swagger: '2.0'
info:
  title: greet-api
  description: Sample API on API Gateway with 2 Google Cloud Functions backends
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://australia-southeast1-wabenwongtest.cloudfunctions.net/Helloworld
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /bye:
    get:
      summary: Greet a user
      operationId: bye
      x-google-backend:
        address: https://australia-southeast1-wabenwongtest.cloudfunctions.net/Byeworld
      responses:
        '200':
          description: A successful response
          schema:
            type: string