swagger: '2.0'
info:
  title: Cloud Endpoints + GCF
  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: hellorun-3mzgkl3dpa-ts.a.run.app
schemes:
  - http
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: http://australia-southeast1-wabenwongtest.cloudfunctions.net/helloGET
        protocol: http/1.1
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /tommy:
    get:
      summary: Greet a user
      operationId: helloTommy
      x-google-backend:
        address: http://australia-southeast1-wabenwongtest.cloudfunctions.net/helloHttp/?name=tom
        protocol: http/1.1
      responses:
        '200':
          description: A successful response
          schema:
            type: string